### ISSUE TITLE
Sato core synchronisation stuck

### ISSUE THREAD

**Issue by johnsmith65463463** [Satoex/Sato#4]
Hello,
Trying to sync my Sato Core Wallet.
It did connect to peers (got up to 7) for a little time, then I get a '0 connection with Sato network' (an X icon in the lower right corner).  I got the botstrap.zip file, good - I'm now stuck at 9 days from now (instead of 33 days), still 0 connection.

Could it be not enough core wallet users online?

**Comment by 4forcebear** [comment]
Download bootstrap.zip file -> https://github.com/Satoex/Sato/releases
1) Open Directory fold (default: %appdata%/Roaming/Sato) and close application
2) Copy file wallet.dat on safe folder
3) remove all files and folders
4) paste content bootsrap.zip into %appdata%/Roaming/Sato
5) open Sato Core and waiting sync
6) Close applictaion and paste has been copyed file wallet.dat
Done! Can open application Sato Core QT.

**Comment by johnsmith65463463** [comment]
Thanks for your answer.

I had already done what you said.

The problem was: I had blacklisted connection (don't know why).
Found that going into Wallet Debug, saw connection list, saw
several blacklisted connections, did un-blacklist.  Then I had connections,
could sync and do transactions.
